name: CMake with vcpkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Set up vcpkg (with caching)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Configure (CMakePresets)
        run: cmake --preset vcpkg

      - name: Build
        run: cmake --build --preset build-${{ matrix.build_type }}

      - name: Run tests
        run: ctest --preset build-${{ matrix.build_type }}

      - name: Package (Release only)
        if: matrix.build_type == 'Release'
        run: cmake --build --preset package-release

      - name: Upload package
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: Tetris-${{ matrix.os }}-${{ matrix.build_type }}
          path: build/Tetris-*.zip
